helloworld: helloworld.rs
	rustc helloworld.rs

runhelloworld: helloworld
	./helloworld

snippet1: snippet1.rs
	rustc snippet1.rs

runsnippet1: snippet1
	./snippet1

runif: p2_if
	./p2_if

runfor: p2_for
	./p2_for

runwhile: p2_while
	./p2_while

runloop: p2_loop
	./p2_loop

runswitch: switch
	./switch

struct: struct.rs
	rustc struct.rs

runstruct: struct
	./struct

array: array.rs
	rustc array.rs

runarray: array
	./array

bool : bool.rs
	rustc bool.rs

runbool: bool
	./bool

control2 : control2.rs
	rustc control2.rs

runcontrol2: control2
	./control2

cootrol : cootrol.rs
	rustc cootrol.rs

runcootrol: cootrol
	./cootrol
	
hello : hello.rs
	rustc hello.rs

runhello: hello
	./hello

int_float: int_float.rs
	rustc int_float.rs

runint_float: int_float
	./int_float
p2_feature : p2_feature.rs
	rustc p2_feature.rs

runx: p2_feature
	./p2_feature

p2_for : p2_for.rs
	rustc p2_for.rs

runp2_for: p2_for
	./p2_for


p2_if : p2_if.rs
	rustc p2_if.rs

runp2_if: p2_if
	./p2_if
	
p2_loop : p2_loop.rs
	rustc p2_loop.rs

runp2_loop: p2_loop
	./p2_loop

p2_while : p2_while.rs
	rustc p2_while.rs

runp2_while: p2_while
	./p2_while

p3_feature : p3_feature.rs
	rustc p3_feature.rs

runp3_feature p3_feature
	./p3_feature

p4_feature : p4_feature.rs
	rustc p4_feature.rs

runp4_feature: p4_feature
	./p4_feature


snippet1 : snippet1.rs
	rustc snippet1.rs

runsnippet1: snippet1
	./snippet1


switch : switch.rs
	rustc switch.rs

runswitch: switch
	./switch


tuple : tuple.rs
	rustc tuple.rs

runtuple: tuple
	./tuple
	
borrow : borrow.rs
	rustc borrow.rs

runborrow: borrow
	./borrow

life : life.rs
	rustc life.rs

runlife: life
	./life
	

p5_feature : p5_feature.rs
	rustc p5_feature.rs

runp5_feature: p5_feature
	./p5_feature

clean:
	find . -depth 1 -type f -not -name '*.rs' -not -name 'Makefile' -delete
